version: "3.8"

networks:
  loki:
    name: loki
    external: true

services:
  grafana:
    image: grafana/grafana:9.1.6
    ports:
    - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    networks:
    - loki
    volumes:
    - ./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml

  prometheus:
    image: prom/prometheus:v2.27.0
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    command: [ '--log.level=debug', '--config.file=/etc/prometheus/prometheus.yml', '--query.lookback-delta=30s', '--enable-feature=remote-write-receiver', '--web.enable-lifecycle']
    networks:
      - loki

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    networks:
      - loki
    container_name: cadvisor
    ports:
    - "3105:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

volumes:
  prometheus:
  grafana:
