global:
  scrape_interval:     15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets:
        - 'prometheus:9090'
- job_name: 'loki'
  dns_sd_configs:
    - names:
        - loki-ingester
        - loki-distributor
      type: A
      port: 3100