version: "3.8"

networks:
  loki:

services:
  loki-gateway:
    image: nginx:1.19
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "3102:3100"
    networks:
      - loki

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler &&
        minio server /data
    environment:
      - MINIO_ACCESS_KEY=loki
      - MINIO_SECRET_KEY=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000:9000"
    volumes:
      - ./.data/minio:/data
    networks:
      - loki

  querier:
    image: grafana/loki:2.6.1
    command: "-config.file=/etc/loki/loki.yaml -target=querier"
    networks:
      - loki
    volumes:
      - ./config:/etc/loki/

  ingester:
    image: grafana/loki:2.6.1
    command: "-config.file=/etc/loki/loki.yaml -target=ingester"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 6
    ports:
      - "3100"
      - "7946"
    volumes:
      - ./config:/etc/loki/

  distributor:
    command: "-config.file=/etc/loki/loki.yaml -target=distributor"
    networks:
      - loki
    image: grafana/loki:2.6.1
    volumes:
      - ./config:/etc/loki/
    ports:
      - "3100"
      - "7946"
    deploy:
      mode: replicated
      replicas: 3

volumes:
  prometheus:
  grafana:
