global:
  scrape_interval:     15s

scrape_configs:
- job_name: 'federate-cluster-a'
  scrape_interval: 15s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{job="loki-cluster-a"}'
  static_configs:
  - targets:
    - 'cluster_a-prometheus-1:9090'

- job_name: cadvisor
  scrape_interval: 15s
  static_configs:
  - targets:
    - cadvisor:8080