version: "3.8"

networks:
  loki:

services:

  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.27.0
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command: [ '--log.level=debug', '--config.file=/etc/prometheus/prometheus.yml', '--query.lookback-delta=30s' ]
    networks:
      - loki

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler &&
        minio server /data
    environment:
      - MINIO_ACCESS_KEY=loki
      - MINIO_SECRET_KEY=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000:9000"
    volumes:
      - ./.data/minio:/data
    networks:
      - loki

  querier:
    image: grafana/loki:2.6.1
    command: "-config.file=/etc/loki/loki.yaml -target=querier"
    networks:
      - loki

  ingester:
    image: grafana/loki:2.6.1
    command: "-config.file=/etc/loki/loki.yaml -target=ingester"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 6
    ports:
      - "3100"
      - "7946"

  distributor:
    command: "-config.file=/etc/loki/loki.yaml -target=distributor"
    image: grafana/loki:2.6.1
    volumes:
      - ./config:/etc/loki/
    ports:
      - "3100"
      - "7946"
    deploy:
      mode: replicated
      replicas: 6

volumes:
  prometheus:
  grafana:
