global:
  scrape_interval:     15s

scrape_configs:
- job_name: 'loki-cluster-d'
  static_configs:
    - labels:
        cluster: d
  dns_sd_configs:
    - names:
        - ingester
        - distributor
        - querier
      type: A
      port: 3100
      refresh_interval: "15s"

- job_name: 'prom'
  scrape_interval: 15s
  static_configs:
  - targets:
    - 'prometheus:9090'
